/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IsuUtamaIndexRouteImport } from './routes/isu-utama/index'
import { Route as ProgramKamiSesiBantuanHidupAsasIndexRouteImport } from './routes/program-kami/sesi-bantuan-hidup-asas/index'
import { Route as ProgramKamiPameranKesihatanIndexRouteImport } from './routes/program-kami/pameran-kesihatan/index'
import { Route as ProgramKamiForumBreatheWellLiveWellIndexRouteImport } from './routes/program-kami/forum-breathe-well-live-well/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IsuUtamaIndexRoute = IsuUtamaIndexRouteImport.update({
  id: '/isu-utama/',
  path: '/isu-utama/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKamiSesiBantuanHidupAsasIndexRoute =
  ProgramKamiSesiBantuanHidupAsasIndexRouteImport.update({
    id: '/program-kami/sesi-bantuan-hidup-asas/',
    path: '/program-kami/sesi-bantuan-hidup-asas/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramKamiPameranKesihatanIndexRoute =
  ProgramKamiPameranKesihatanIndexRouteImport.update({
    id: '/program-kami/pameran-kesihatan/',
    path: '/program-kami/pameran-kesihatan/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramKamiForumBreatheWellLiveWellIndexRoute =
  ProgramKamiForumBreatheWellLiveWellIndexRouteImport.update({
    id: '/program-kami/forum-breathe-well-live-well/',
    path: '/program-kami/forum-breathe-well-live-well/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/isu-utama': typeof IsuUtamaIndexRoute
  '/program-kami/forum-breathe-well-live-well': typeof ProgramKamiForumBreatheWellLiveWellIndexRoute
  '/program-kami/pameran-kesihatan': typeof ProgramKamiPameranKesihatanIndexRoute
  '/program-kami/sesi-bantuan-hidup-asas': typeof ProgramKamiSesiBantuanHidupAsasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/isu-utama': typeof IsuUtamaIndexRoute
  '/program-kami/forum-breathe-well-live-well': typeof ProgramKamiForumBreatheWellLiveWellIndexRoute
  '/program-kami/pameran-kesihatan': typeof ProgramKamiPameranKesihatanIndexRoute
  '/program-kami/sesi-bantuan-hidup-asas': typeof ProgramKamiSesiBantuanHidupAsasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/isu-utama/': typeof IsuUtamaIndexRoute
  '/program-kami/forum-breathe-well-live-well/': typeof ProgramKamiForumBreatheWellLiveWellIndexRoute
  '/program-kami/pameran-kesihatan/': typeof ProgramKamiPameranKesihatanIndexRoute
  '/program-kami/sesi-bantuan-hidup-asas/': typeof ProgramKamiSesiBantuanHidupAsasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/isu-utama'
    | '/program-kami/forum-breathe-well-live-well'
    | '/program-kami/pameran-kesihatan'
    | '/program-kami/sesi-bantuan-hidup-asas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/isu-utama'
    | '/program-kami/forum-breathe-well-live-well'
    | '/program-kami/pameran-kesihatan'
    | '/program-kami/sesi-bantuan-hidup-asas'
  id:
    | '__root__'
    | '/'
    | '/isu-utama/'
    | '/program-kami/forum-breathe-well-live-well/'
    | '/program-kami/pameran-kesihatan/'
    | '/program-kami/sesi-bantuan-hidup-asas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IsuUtamaIndexRoute: typeof IsuUtamaIndexRoute
  ProgramKamiForumBreatheWellLiveWellIndexRoute: typeof ProgramKamiForumBreatheWellLiveWellIndexRoute
  ProgramKamiPameranKesihatanIndexRoute: typeof ProgramKamiPameranKesihatanIndexRoute
  ProgramKamiSesiBantuanHidupAsasIndexRoute: typeof ProgramKamiSesiBantuanHidupAsasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isu-utama/': {
      id: '/isu-utama/'
      path: '/isu-utama'
      fullPath: '/isu-utama'
      preLoaderRoute: typeof IsuUtamaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-kami/sesi-bantuan-hidup-asas/': {
      id: '/program-kami/sesi-bantuan-hidup-asas/'
      path: '/program-kami/sesi-bantuan-hidup-asas'
      fullPath: '/program-kami/sesi-bantuan-hidup-asas'
      preLoaderRoute: typeof ProgramKamiSesiBantuanHidupAsasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-kami/pameran-kesihatan/': {
      id: '/program-kami/pameran-kesihatan/'
      path: '/program-kami/pameran-kesihatan'
      fullPath: '/program-kami/pameran-kesihatan'
      preLoaderRoute: typeof ProgramKamiPameranKesihatanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-kami/forum-breathe-well-live-well/': {
      id: '/program-kami/forum-breathe-well-live-well/'
      path: '/program-kami/forum-breathe-well-live-well'
      fullPath: '/program-kami/forum-breathe-well-live-well'
      preLoaderRoute: typeof ProgramKamiForumBreatheWellLiveWellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IsuUtamaIndexRoute: IsuUtamaIndexRoute,
  ProgramKamiForumBreatheWellLiveWellIndexRoute:
    ProgramKamiForumBreatheWellLiveWellIndexRoute,
  ProgramKamiPameranKesihatanIndexRoute: ProgramKamiPameranKesihatanIndexRoute,
  ProgramKamiSesiBantuanHidupAsasIndexRoute:
    ProgramKamiSesiBantuanHidupAsasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
